flaskchat/models.py
# -*- coding: utf-8 -*-

import datetime
import calendar

from flask import json
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.security import RoleMixin, UserMixin

db = SQLAlchemy()

roles_users = db.Table('roles_users',
                       db.Column('role_id', db.Integer(),
                                 db.ForeignKey('roles.id'), primary_key=True),
                       db.Column('user_id', db.Integer(),
                                 db.ForeignKey('users.id'), primary_key=True))


users_chat_subscriptions = db.Table('users_chat_subscriptions',
                                    db.Column('user_id', db.Integer(),
                                              db.ForeignKey('users.id'),
                                              primary_key=True),
                                    db.Column('chat_id', db.Integer(),
                                              db.ForeignKey('chats.id'),
                                              primary_key=True))


class Role(db.Model, RoleMixin):
    __tablename__ = 'roles'

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __repr__(self):
        return '<Role {}>'.format(self.name)


class Chat(db.Model):
    __tablename__ = 'chats'

    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(128), unique=True)

    def __repr__(self):
        return '<Chat {}>'.format(self.title)


class ChatMessage(db.Model):
    __tablename__ = 'chat_messages'

    id = db.Column(db.Integer(), primary_key=True)
    text = db.Column(db.Text())
    created_at = db.Column(db.DateTime(), index=True,
                           default=datetime.datetime.utcnow)
    chat_id = db.Column(db.Integer(), db.ForeignKey('chats.id'))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    chat = db.relationship('Chat', backref=db.backref('messages',
                                                      lazy='dynamic'))
    user = db.relationship('User', backref=db.backref('chat_messages',
                                                      lazy='dynamic'))

    def __repr__(self):
        return '<ChatMessage from {}>'.format(self.user.username)

    def to_dict(self):
        return {
            'id': self.id,
            'created_at': calendar.timegm(self.created_at.timetuple()) * 1000,
            'author': self.user.username,
            'text': self.text
        }


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(255), unique=True)
    username = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))
    chat_subscriptions = db.relationship(
        'Chat',
        secondary=users_chat_subscriptions,
        backref='subscribed_users')

    def is_subscribed_to_chat(self, chat):
        return chat in self.chat_subscriptions

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def to_dict(self):
        return {
            'username': self.username
        }

    def to_json(self):
        return json.dumps(self.to_dict())

flaskchat/forms.py
# -*- coding: utf-8 -*-

from flask import current_app
from werkzeug.local import LocalProxy
from flask.ext.security import forms
from flask.ext.wtf import Form
from wtforms import StringField, ValidationError
from wtforms.validators import DataRequired, Length

from flaskchat.models import Chat


_datastore = LocalProxy(lambda: current_app.extensions['security'].datastore)


def unique_username(form, field):
    if _datastore.find_user(username=field.data) is not None:
        raise ValidationError('This username already exists')


def unique_chat_name(form, field):
    if Chat.query.filter_by(title=field.data).first() is not None:
        raise ValidationError('Chat with this title already exists')


class ConfirmRegisterForm(forms.ConfirmRegisterForm):
    username = StringField('Username', validators=[
        DataRequired('This field is required'),
        Length(min=1, max=255,
               message='Username must be between 1 and 255 characters long'),
        unique_username])


class CreateChatForm(Form):
    title = StringField('Title', validators=[
        DataRequired('This field is required'),
        Length(min=1, max=128,
               message='Chat title must be between 1 and 128 characters long'),
        unique_chat_name])


class SearchChatForm(Form):
    term = StringField('Search chat')

flaskchat/__init__.py
# -*- coding: utf-8 -*-

flaskchat/api/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

api = Blueprint('api', __name__, template_folder='templates')

import flaskchat.api.views

flaskchat/api/views.py
# -*- coding: utf-8 -*-

from datetime import datetime

from flask import request, abort, current_app, jsonify
from werkzeug.local import LocalProxy
from flask.ext.security.decorators import login_required

from flaskchat.api import api
from flaskchat.models import db, Chat, ChatMessage

_datastore = LocalProxy(lambda: current_app.extensions['security'].datastore)


@api.route('/chat/<int:chat_id>/messages', methods=['POST'])
@login_required
def save_message(chat_id):
    chat = Chat.query.get_or_404(chat_id)
    json = request.get_json()
    username = json.get('author')
    text = json.get('text')
    created_at = json.get('created_at')

    if not all([username, text, created_at]):
        abort(400)

    user = _datastore.find_user(username=username)
    if not user:
        abort(400)

    message = ChatMessage()
    message.user = user
    message.chat = chat
    message.text = text
    message.created_at = datetime.utcfromtimestamp(created_at // 1000)

    db.session.add(message)
    db.session.commit()

    return ''


@api.route('/chat/<int:chat_id>/messages', methods=['GET'])
@login_required
def get_messages(chat_id):
    chat = Chat.query.get_or_404(chat_id)
    messages = [m.to_dict() for m in chat.messages.all()]
    return jsonify(result=messages)


@api.route('/chat/<int:chat_id>/users', methods=['GET'])
def get_users(chat_id):
    chat = Chat.query.get_or_404(chat_id)
    users = [u.to_dict() for u in chat.subscribed_users]
    return jsonify(result=users)

flaskchat/app.py
# -*- coding: utf-8 -*-

from flask import Flask


def create_app(config_file_name):
    app = Flask('flaskchat', instance_relative_config=True)
    app.config.from_object('flaskchat.settings')
    app.config.from_pyfile(config_file_name)

    _init_db(app)
    _init_mail(app)
    _init_security(app)
    _init_blueprints(app)
    _init_context_processors(app)

    return app


def _init_db(app):
    from flaskchat.models import db
    db.init_app(app)


def _init_mail(app):
    from flaskchat.mail import mail
    mail.init_app(app)


def _init_security(app):
    from flaskchat.security import security, user_datastore
    from flaskchat.forms import ConfirmRegisterForm
    security.init_app(app, datastore=user_datastore,
                      confirm_register_form=ConfirmRegisterForm)


def _init_blueprints(app):
    from flaskchat.core import core
    app.register_blueprint(core)

    from flaskchat.chat import chat
    app.register_blueprint(chat, url_prefix='/chat')

    from flaskchat.api import api
    app.register_blueprint(api, url_prefix='/api')


def _init_context_processors(app):
    from flaskchat.forms import SearchChatForm

    @app.context_processor
    def add_chat_search_form():
        return {'chat_search_form': SearchChatForm()}

flaskchat/chat/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

chat = Blueprint('chat', __name__, template_folder='templates')

import flaskchat.chat.views

flaskchat/chat/views.py
# -*- coding: utf-8 -*-

from flask import (render_template, redirect, url_for, request, current_app,
                   abort, json)
from flask.ext.security.decorators import login_required
from flask.ext.security.core import current_user

from flaskchat.chat import chat
from flaskchat.forms import CreateChatForm
from flaskchat.models import db, Chat


@chat.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CreateChatForm()

    if form.validate_on_submit():
        c = Chat()
        c.title = form.title.data
        c.subscribed_users.append(current_user)
        db.session.add(c)
        db.session.commit()

        return redirect(url_for('chat.show', chat_id=c.id))

    return render_template('chat/create.html', form=form)


@chat.route('/search')
@chat.route('/search/<int:page>')
@login_required
def search(page=1):
    term = request.args.get('term', '')
    page = page if page > 0 else 1
    per_page = current_app.config['CHAT_SEARCH_PER_PAGE']

    pagination = (Chat.query
                  .filter(Chat.title.ilike(u'%{}%'.format(term)))
                  .order_by('title')
                  .paginate(page, per_page))

    return render_template('chat/search.html', term=term,
                           pagination=pagination)


@chat.route('/list')
@chat.route('/list/<int:page>')
@login_required
def list(page=1):
    page = page if page > 0 else 1
    per_page = current_app.config['CHAT_LIST_PER_PAGE']
    pagination = Chat.query.order_by('title').paginate(page, per_page)

    return render_template('chat/list.html', pagination=pagination)


@chat.route('/subscribe/<int:chat_id>', methods=['POST'])
@login_required
def subscribe(chat_id):
    chat = Chat.query.get_or_404(chat_id)
    if not current_user.is_subscribed_to_chat(chat):
        current_user.chat_subscriptions.append(chat)
        db.session.commit()

    return redirect(url_for('chat.show', chat_id=chat_id))


@chat.route('/unsubscribe/<int:chat_id>', methods=['POST'])
@login_required
def unsubscribe(chat_id):
    chat = Chat.query.get_or_404(chat_id)
    if current_user.is_subscribed_to_chat(chat):
        current_user.chat_subscriptions.remove(chat)
        db.session.commit()

    return redirect(url_for('core.index'))


@chat.route('/show/<int:chat_id>')
@login_required
def show(chat_id):
    chat = Chat.query.get_or_404(chat_id)
    if not current_user.is_subscribed_to_chat(chat):
        abort(404)

    users_json = json.dumps([u.to_dict() for u in chat.subscribed_users])
    messages_json = json.dumps([m.to_dict() for m in chat.messages.all()])

    return render_template('chat/show.html', active_chat=chat,
                           initial_users_json=users_json,
                           initial_messages_json=messages_json)

flaskchat/core/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

core = Blueprint('core', __name__, template_folder='templates')

import flaskchat.core.views

flaskchat/core/views.py
# -*- coding: utf-8 -*-

from flask import render_template

from flaskchat.core import core


@core.route('/')
def index():
    return render_template('index.html')

flaskchat/templates/chat/create.html
{% extends 'base.html' %}
{% from 'macros.html' import form_field %}

{% block content %}
  <h1>Create chat</h1>
  <div class="row">
    <div class="col-lg-9">
      <form class="form-horizontal" action="{{ url_for('chat.create') }}" method="POST">
        {{ form.hidden_tag() }}
        {{ form_field(form.title) }}

        <div class="form-group">
          <div class="col-sm-9"></div>
          <div class="col-sm-3">
            <input class="form-control btn btn-primary" type="submit" value="Create" />
          </div>
        </div>
      </form>
    </div>
    <div class="col-lg-3"></div>
  </div>
{% endblock %}

flaskchat/templates/chat/list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Chat list</h1>

  {% if pagination.items %}
    <table class="table-striped table-hover" style="width:500px;">
      <tbody>
        {% for item in pagination.items %}
          <tr style="height:35px;">
            <td style="width:450px; padding: 5px 5px 5px 5px;">{{ item.title }}</td>
            <td>
              {% if not current_user.is_subscribed_to_chat(item) %}
              <form method="POST" action="{{ url_for('chat.subscribe', chat_id=item.id) }}">
              <input class="btn btn-default" type="submit" value="Join" />
              </form>
              {% endif %}
            <td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if pagination.pages > 1 %}
      <ul class="pagination">
        <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
          {% if pagination.has_prev %}
            <a href="{{ url_for('chat.list', page=pagination.prev_num) }}">«</a>
          {% else %}
            <a href="javascript:void(0);">«</a>
          {% endif %}
        </li>
        {% for page in pagination.iter_pages() %}
          {% if page %}
            <li {% if page == pagination.page %}class="active"{% endif %}>
              {% if page == pagination.page %}
                <a href="javascript:void(0);">{{ page }}</a>
              {% else %}
                <a href="{{ url_for('chat.list', page=page) }}">{{ page }}</a>
              {% endif %}
            </li>
          {% else %}
            <li><a href="javascript:void(0);">...</a></li>
          {% endif %}
        {% endfor %}
        <li {% if not pagination.has_next %}class="disabled"{% endif %}>
          {% if pagination.has_next %}
            <a href="{{ url_for('chat.list', page=pagination.next_num) }}">»</a>
          {% else %}
            <a href="javascript:void(0);">»</a>
          {% endif %}
        </li>
      </ul>
    {% endif %}
  {% endif %}

{% endblock %}

flaskchat/templates/chat/search.html
{% extends 'base.html' %}

{% block content %}
  <h1>Search</h1>

  {% if pagination.total %}
    <p>Results: {{ pagination.total }}</p>
  {% else %}
    <p>Sorry, nothing was found</p>
  {% endif %}

  {% if pagination.items %}
    <table class="table-striped table-hover" style="width:500px;">
      <tbody>
        {% for item in pagination.items %}
          <tr style="height:35px;">
            <td style="width:450px; padding: 5px 5px 5px 5px;">{{ item.title }}</td>
            <td>
              {% if not current_user.is_subscribed_to_chat(item) %}
              <form method="POST" action="{{ url_for('chat.subscribe', chat_id=item.id) }}">
              <input class="btn btn-default" type="submit" value="Join" />
              </form>
              {% endif %}
            <td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if pagination.pages > 1 %}
      <ul class="pagination">
        <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
          {% if pagination.has_prev %}
            <a href="{{ url_for('chat.search', page=pagination.prev_num) }}?term={{ term }}">«</a>
          {% else %}
            <a href="javascript:void(0);">«</a>
          {% endif %}
        </li>
        {% for page in pagination.iter_pages() %}
          {% if page %}
            <li {% if page == pagination.page %}class="active"{% endif %}>
              {% if page == pagination.page %}
                <a href="javascript:void(0);">{{ page }}</a>
              {% else %}
                <a href="{{ url_for('chat.search', page=page) }}?term={{ term }}">{{ page }}</a>
              {% endif %}
            </li>
          {% else %}
            <li><a href="javascript:void(0);">...</a></li>
          {% endif %}
        {% endfor %}
        <li {% if not pagination.has_next %}class="disabled"{% endif %}>
          {% if pagination.has_next %}
            <a href="{{ url_for('chat.search', page=pagination.next_num) }}?term={{ term }}">»</a>
          {% else %}
            <a href="javascript:void(0);">»</a>
          {% endif %}
        </li>
      </ul>
    {% endif %}
  {% endif %}

{% endblock %}

flaskchat/templates/chat/show.html
{% extends 'base.html' %}

{% block content %}
  <div style="width: 670px;">
    <div class="pull-right" style="width:150px; height:400px;">
      <h4>Users</h4>
      <div class="well well-lg" style="width:150px; height:360px; overflow:auto;" id="users-region"></div>
      <form method="POST" action="{{ url_for('chat.unsubscribe', chat_id=active_chat.id) }}">
        <input class="btn btn-primary" type="submit" value="Leave chat">
      </form>
    </div>
    <div id="chat-messages-region"></div>
    <div id="message-input-region"></div>
  </div>

  <script type="text/html" id="tpl-chat-message-view">
  <p>
    <span style="color: red;">[<%= formattedDate() %>]</span>
    <span style="color:blue;"><%- author %>:</span>
    <span><%- text %></span>
  </p>
  </script>

  <script type="text/html" id="tpl-user-view">
  <p><%- username %></p>
  </script>

  <script type="text/html" id="tpl-message-input">
    <textarea id="message-input" style="width:500px; height: 50px;"/>
  </script>

  <script type="text/html" id="tpl-chat-message-list">
    <div id="chat-messages-container" class="well well-lg pull-left" style="width:500px; height:400px; overflow:auto;"></div>
  </script>
{% endblock %}

{% block javascripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.autosize.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/moment.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/underscore-min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/backbone.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/backbone.marionette.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/chat/ChatApp.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/chat/ChatApp.Models.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/chat/ChatApp.Views.js') }}"></script>
{% endblock %}

{% block custom_js %}
  {{ super() }}

  $(document).ready(function() {
      window.CHAT_ID = {{ active_chat.id }}

      var users = new ChatApp.Models.UserList({{ initial_users_json|safe }}),
          messages = new ChatApp.Models.ChatMessageList({{ initial_messages_json|safe }}),
          currentUser = new ChatApp.Models.User({{ current_user.to_json()|safe }});

      ChatApp.start({
          'users': users,
          'messages': messages,
          'currentUser': currentUser
      });
  });
{% endblock %}